/*

    main.sql

    Created by JO HYUK JUN on 2023
    Copyright © 2023 JO HYUK JUN. All rights reserved.

*/


SELECT USED_GOODS_BOARD.TITLE, USED_GOODS_BOARD.BOARD_ID, USED_GOODS_REPLY.REPLY_ID, USED_GOODS_REPLY.WRITER_ID, USED_GOODS_REPLY.CONTENTS, DATE_FORMAT(USED_GOODS_REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD, USED_GOODS_REPLY
WHERE DATE_FORMAT(USED_GOODS_BOARD.CREATED_DATE, '%Y-%m-%d') BETWEEN '2022-10-01' AND '2022-10-31' AND USED_GOODS_BOARD.BOARD_ID = USED_GOODS_REPLY.BOARD_ID
ORDER BY DATE_FORMAT(USED_GOODS_REPLY.CREATED_DATE, '%Y-%m-%d'), USED_GOODS_BOARD.TITLE