/*

    main.sql

    Created by JO HYUK JUN on 2023
    Copyright © 2023 JO HYUK JUN. All rights reserved.

*/


SELECT CONCAT('/home/grep/src/', USED_GOODS_FILE.BOARD_ID, '/', USED_GOODS_FILE.FILE_ID, USED_GOODS_FILE.FILE_NAME, USED_GOODS_FILE.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD, USED_GOODS_FILE
WHERE USED_GOODS_BOARD.BOARD_ID = USED_GOODS_FILE.BOARD_ID AND USED_GOODS_BOARD.VIEWS = (SELECT MAX(USED_GOODS_BOARD.VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_PATH DESC